class RussianButtonHeadings:
    #
    BACK_HEADING = "⬅Назад"
    MAIN_MENU_HEADING = "Главное меню"
    NEW_ORDER_HEADING = "Новый заказ!"
    ACTIVE_ORDERS_HEADING = "Активные заказы."
    MY_PROFILE_HEADING = "Мой профиль."
    BALANCE_HEADING = "Баланс:"
    SUPPORT_HEADING = "Поддержка."
    REVIEWS_HEADING = "Отзывы"
    AFFILIATE_PROGRAM_HEADING = "Партнёрская программа."
    SOLVER_MENU_HEADING = "Меню решателя."
    CONTROL_PANEL_HEADING = "Панель управления."
    CUSTOM_MENU_HEADING = "Пользовательское меню."
    YES_BUTTON_HEADING = "Да"
    NO_BUTTON_HEADING = "Нет"
    USER_SUBSCRIPTION_CHECK_HEADING = "Да, я подписался(лась).\nYes, I signed up."
    #new order menu
    NEW_ORDER_BY_ADMIN_HEADING = "Заказ через админа"
    NEW_ORDER_BY_BOT_HEADING = "Заказ через бота"
    UNFINISHED_ORDER_HEADING = "Незавершённый заказ"
    UP_ORDER_SETTINGS_HEADING = "Доп. настройки"
    #new order menu: order format
    STANDART_IMPORTANCE_HEADING = "Стандартный заказ"
    NOW_IMPORTANCE_HEADING = "Прямо сейчас"
    IMPORTANT_IMPORTANCE_HEADING = "Онлайн помощь"
    VOLUMINOUS_IMPORTANCE_HEADING = "Объёмный заказ"
    #new order menu:    standart order main menu
    NEW_STANDART_ORDER_IMPORTANCE_HEADING = "Стандартный заказ:"
    NEW_STANDART_ORDER_SUBJECT_HEADING = "Предмет:  "
    NEW_STANDART_ORDER_COMMENT_HEADING = "Описание:  "
    NEW_STANDART_ORDER_FILES_HEADING = "Файлы:  "
    NEW_STANDART_ORDER_DEADLINE_TIME_HEADING = "Дедлайн:  "
    SEND_ORDER_TO_SOLVERS_HEADING = "Отправить заказ!"
    #get order time
    GET_ORDER_TIME_HEADING = "23:59"
    ORDER_1DURATION_HEADING = "00:30"
    ORDER_2DURATION_HEADING = "00:45"
    ORDER_3DURATION_HEADING = "01:00"
    ORDER_4DURATION_HEADING = "01:30"
    ORDER_5DURATION_HEADING = "02:00"
    ORDER_6DURATION_HEADING = "03:00"
    ORDER_7DURATION_HEADING = "04:30"
    ORDER_8DURATION_HEADING = "06:00"
    #get order files
    CONFIRM_FILES_HEADING = "Подтвердить"
    DELETE_ALL_FILES_HEADING = "Удалить все файлы заказа"
    #order formats
    CONTROL_FORMAT_HEADING = "Контрольная"
    HOMEWORK_FORMAT_HEADING = "ДЗ"
    EXAM_FORMAT_HEADING = "Экзамен"
    LABA_FORMAT_HEADING = "Лаба"
    COURSEWORK_FORMAT_HEADING = "Курсач"
    DIPLOMA_FORMAT_HEADING = "Диплом"
    OTHER_FORMAT_HEADING = "Другое"
    #get order percent
    TEN_PERCENT_HEADING = "10"
    TWENTY_PERCENT_HEADING = "20"
    THIRTY_PERCENT_HEADING = "30"
    FORTY_PERCENT_HEADING = "40"
    FIFTY_PERCENT_HEADING = "50"
    SIXTY_PERCENT_HEADING = "60"
    SEVENTY_PERCENT_HEADING = "70"
    EIGHTY_PERCENT_HEADING = "80"
    NINETY_PERCENT_HEADING = "90"
    HUNDRED_PERCENT_HEADING = "100"
    #additional order settings
    SUPPORT_ORDER_SETTING_HEADING = "Поддержка заказа"
    PERCENT_COMPLET_ORDER_SETTING_HEADING = "Процент выполнения"
    PREFERRED_BUDGET_ORDER_SETTING_HEADING = "Предпочитаемый бюджет"
    TYPE_ORDER_SETTING_HEADING = "Тип работы"

    """Orders and topics keyboards:"""
    MATHS_SUBJECT_HEADING = "Математика"
    PHYSICS_SUBJECT_HEADING = "Физика"
    IT_SUBJECT_HEADING = "IT"
    ENGINEERING_SUBJECT_HEADING = "Инженерия"
    ECONOMY_SUBJECT_HEADING = "Экономика"
    CHEMISTRY_SUBJECT_HEADING = "Химия"
    LANGUAGES_SUBJECT_HEADING = "Языки"
    BIOLOGY_SUBJECT_HEADING = "Биология"
    GEOGRAPHY_SUBJECT_HEADING = "География"
    HUMANITARIAN_SUBJECT_HEADING = "Гуманитарные предметы"
    REGISTRATION_SUBJECT_HEADING = "Оформление работы"
    OTHER_SUBJECT_HEADING = "Остальное"

    #maths topic keyboard
    CALCULUS_OF_VARIATIONS_HEADING = "Вариационное исчисление"
    VECTOR_TENSOR_ANALYSIS_HEADING = "Векторно-тензорный анализ"
    COMPUTATIONAL_MATHEMATICS_HEADING = "Вычислительная математика"
    DISCRETE_MATHEMATICS_HEADING = "Дискретная математика"
    DIFFUSIONS_HEADING = "Диффуры"
    MULTIPLE_INTEGRALS_HEADING = "Кратные интегралы"
    MATHEMATICAL_ANALYSIS_HEADING = "Матан"
    MATHEMATICAL_MODELING_HEADING = "Мат. моделирование"
    SYSTEM_ANALYSIS_AND_DECISION_MAKING_HEADING = "Системный анализ и принятие решений"
    TFCP_HEADING = "ТФКП"
    ANALYTICAL_GEOMETRY_HEADING = "Аналитическая геометрия"
    LINEAR_ALGEBRA_HEADING = "Линал"
    MATHEMATICAL_STATISTICS_HEADING = "Матстаты"
    ROWS_HEADING = "Ряды"
    PROBABILITY_THEORY_HEADING = "Теорвер"
    TOPOLOGY_HEADING = "Топология"
    UMF_HEADING = "УМФ"
    FUNCTIONAL_ANALYSIS_HEADING = "Функан"                                         
    FUNCTIONS_OF_MULTIPLE_VARIABLES_HEADING = "Функции нескольких переменных"                 
    OTHER_MATHS_HEADING = "Другое"

    #physics                       
    QUANTUM_MECHANICS_HEADING = "Квантовая механика"
    MATERIALS_SCIENCE_HEADING = "Материаловедение"
    METROLOGY_HEADING = "Метрология"
    MECHANICS_HEADING = "Механика"
    FLUID_AND_GAS_MECHANICS_HEADING = "Механика жидкости и газа"
    OPTICS_HEADING = "Оптика"
    STRENGTH_OF_MATERIALS_HEADING = "Сопромат"
    THEORETICAL_MECHANICS_HEADING = "Теормех"
    ELECTRICITY_HEADING = "Электричество"
    OTHER_PHYSICS_HEADING = "Другое"

    #IT
    BASIC_IT_HEADING = "BASIC"
    C_IT_HEADING = "C"
    C_SHARP_IT_HEADING = "C#"
    C_PLUS_PLUS_IT_HEADING = "C++"
    DELPHI_IT_HEADING = "DELPHI"
    EXCEL_IT_HEADING = "EXCEL"
    JAVA_IT_HEADING = "JAVA"
    JAVA_SCRIPT_HEADING = "JAVA_SCRIPT"
    GO_IT_HEADING = "GO"
    MATLAB_IT_HEADING = "MATLAB"
    PYTHON_IT_HEADING = "PYTHON"
    PHP_IT_HEADING = "PHP"
    DATA_BASE_IT_HEADING = "DATA_BASE"
    LATEX_IT_HEADING = "LATEX"
    LAZARUS_HEADING = "LAZARUS"
    PASCAL_IT_HEADING = "PASCAL"
    R_IT_HEADING = "R"
    OTHER_IT_HEADING = "Другое"
    #engineering
    ENGINEERING_GRAPHICS_HEADING = "Инженерная графика"
    DESCRIPTIVE_GEOMETRY_HEADING = "Начертательная геометрия"
    CIRCUITRY_AND_MECHATRONICS_HEADING = "Схемотехника и мехатроника"
    THEORY_OF_MECHANISMS_AND_MACHINES_HEADING = "Теория механизмов и машин"
    TECHNOLOGY_OF_STRUCTURAL_MATERIALS_HEADING = "Технология конструкционных материалов"
    ELECTRONICS_HEADING = "Электроника"
    ELECTRONIC_BOARDS_AND_COMPONENTS_HEADING = "Электронные платы и компоненты"
    ELECTRICAL_ENGINEERING_HEADING = "Электротехника"
    ANALYTICAL_MECHANICS_HEADING = "Аналитическая механика"
    MACHINES_HEADING = "Станки"
    OTHER_ENGINEERING_HEADING = "Другое"
    #economy
    LOGISTICS_HEADING = "Логистика"
    MACROECONOMICS_HEADING = "Макроэкономика"
    MARKETING_HEADING = "Маркетинг"
    MANAGEMENT_HEADING = "Менеджмент"
    MICROECONOMICS_HEADING = "Микроэкономика"
    TAXATION_HEADING = "Налогообложение"
    PERSONNEL_MANAGEMENT_HEADING = "Управление персоналом"
    ECONOMY_HEADING = "Экономика"
    ACCOUNTING_HEADING = "Бухгалтерский учет"
    ECONOMETRICS_HEADING = "Эконометрика"
    OTHER_ECONOMY_HEADING = "Другое"
    #chemistry
    ORGANIC_CHEMISTRY_HEADING = "Органическая химия"
    ANALYTICAL_CHEMISTRY_HEADING = "Аналитическая химия"
    GENERAL_CHEMISTRY_HEADING = "Общая химия"
    BIOCHEMISTRY_HEADING = "Биохимия"
    PHYSICAL_CHEMISTRY_HEADING = "Физическая химия"
    INORGANIC_CHEMISTRY_HEADING = "Неорганическая химия"
    OTHER_CHEMISTRY_HEADING = "Другое"
    #languages
    RUSSIAN_HEADING = "Русский"
    CHINESE_HEADING = "Китайский"
    ENGLISH_HEADING = "Английский"
    FRENCH_HEADING = "Французский"
    GERMAN_HEADING = "Немецкий"
    SPANISH_HEADING = "Испанский"
    OTHER_LANGUAGES_HEADING = "Другое"
    #biology
    ANATOMY_HEADING = "Анатомия"
    PARASITOLOGY_HEADING = "Паразитология"
    BIOINFORMATICS_HEADING = "Биоинформатика"
    MICROBIOLOGY_HEADING = "Микробиология"
    BOTANY_HEADING = "Ботаника"
    MOLECULAR_BIOLOGY_HEADING = "Молекулярная биология"
    ZOOLOGY_HEADING = "Зоология"
    GENETICS_HEADING = "Генетика"
    VIROLOGY_HEADING = "Вирусология"
    OTHER_BIOLOGY_HEADING = "Другое"
    #geography
    GEOGRAPHY_HEADING = "География"
    #humanitarian
    HISTORY_HEADING = "История"
    DESIGN_HEADING = "Дизайн"
    OBZH_HEADING = "ОБЖ"
    PHILOSOPHY_HEADING = "Философия"
    LAW_HEADING = "Право"
    OTHER_HUMANITARIAN_HEADING = "Другое"
    #registration
    REGISTRATION_HEADING = "Оформление работы"

    """End---------------------------------------------------------------------------------------"""

    #my profile menu
    SET_BANKING_DETAILS_HEADINGS = "Задать реквизиты"
    SET_CURRENCY_HEADINGS = "Задать валюту"
    SET_LANGUAGE_HEADING = "Задать язык"
    #balance menu
    CASH_IN_HEADING = "Пополнить баланс"
    CASH_OUT_HEADING = "Вывести средства"
    #support menu
    BECOME_A_PARTNER_HEADING = "Стать партнёром"
    BECOME_A_SOLVER_HEADING = "Стать решателем"
    ASK_A_QUESTION_HEADING = "Задать вопрос"
    FAQ_HEADING = "FAQ"
    #support FAQ menu
    FAQ_FOR_CLIENTS_HEADING = "FAQ для пользователей"
    FAQ_FOR_SOLVERS_HEADING = "FAQ для решателей"
    FAQ_FOR_PARTNERS_HEADING = "FAQ для партнёров"
    #affiliate program menu
    LIST_AFFILIATE_LINKS_HEADING = "Список ссылок"
    CREATE_AFFILIATE_LINK_HEADING = "Создать ссылку"
    AFFILIATE_PROGRAM_STATISTICS_HEADING = "Статистика"

    NONE_VALUE = "❓"
    DONE_VALUE = "✔️"

    NEW_NOW_ORDER_NUMBER_OF_TASKS_HEADING = "Количество задач:"
    NEW_IMPORTANT_ORDER_DURATION_TIME_HEADING = "Длительность работы:"
    LAST_MONTH = "<---"
    NEXT_MONTH = "--->"